version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_DATABASE=studentdb
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
